name: get_outfit
description: Get Outfit Quiz.

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  crypto: ^2.1.4
  cupertino_icons: ^0.1.2
  easy_web_view: ^1.3.0
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  shared_preferences: ^0.5.7+3
  uuid: ^2.0.4

dev_dependencies:
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.7.4
  json_serializable: ^3.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/FuturaPT-Bold.ttf
    - family: FuturaBook
      fonts:
        - asset: assets/fonts/FuturaPT-Book.ttf
    - family: FuturaDemi
      fonts:
        - asset: assets/fonts/FuturaPT-Demi.ttf
    - family: FuturaMedium
      fonts:
        - asset: assets/fonts/FuturaPT-Medium.ttf
